apiVersion: v1
kind: Service
metadata:
  name: clerint-website
  namespace: clerint
spec:
  selector:
    app: clerint-website
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30500
      protocol: TCP
  type: NodePort
